services:

  library-database:
      image: postgres:16.2-alpine3.19
      environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=book-items
      ports:
        - "14001:5432"